name: Check Code Quality

on:
  push:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Dependencies
        run: pnpm install
      - name: Synchronize SvelteKit
        run: pnpm sync
      - name: Run Linters
        run: pnpm lint
        env:
          PUBLIC_WEBSOCKET_URL: ${{ vars.PUBLIC_WEBSOCKET_URL }}
          PUBLIC_WEBSOCKET_ID: ${{ vars.PUBLIC_WEBSOCKET_ID }}
