name: Check Code Quality

on:
  push:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Dependencies and Sync
        run: pnpm install && pnpm sync
      - name: Run Linters
        run: pnpm lint
        env:
          PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
          PUBLIC_USER_ID: ${{ vars.PUBLIC_USER_ID }}
